# project tasks
[tasks.api-run]
workspace = false
env = { RUST_LOG="info" }
install_crate = "cargo-shuttle"
command = "cargo"
args = ["shuttle", "run"]

[tasks.api-run-actix]
workspace = false
command = "cargo"
args = ["run", "--bin", "api-actix"]

[tasks.front-serve]
workspace = false
cwd = "./front"
install_crate = "dioxus-cli"
command = "dioxus"
args = ["serve"]

[tasks.front-build]
workspace = false
script_runner = "@shell"
script = '''
rm -rf api/shuttle/static
mkdir api/shuttle/static
cd front
dioxus build --release
# local development 
# shuttle issue with static files
# location is different depending on the environment
cp -r dist/* ../api/shuttle/static
# production
cp -r dist/* ../static
'''

# local db
[tasks.db-start]
workspace = false
script_runner = "@shell"
script = '''
docker run -d --name devbcn-workshop -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=devbcn postgres
'''

[tasks.db-stop]
workspace = false
script_runner = "@shell"
script = '''
docker stop postgres
docker rm postgres
'''

# general tasks
[tasks.clippy]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.format]
clear = true
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

# book tasks
[tasks.book-readme]
workspace = false
script_runner = "@shell"
script = '''
cp README.md docs/src/README.md
sed -i 's/\.\/docs\/src\//\.\//g' docs/src/README.md
'''

[tasks.book-preprocessors]
workspace = false
script_runner = "@shell"
script = '''
cargo install mdbook-mermaid
cargo install mdbook-admonish
cargo install mdbook-toc
'''

[tasks.book-build-ci]
workspace = false
run_task = { name = [ "book-readme", "book-build-inner"] }

[tasks.book-build]
workspace = false
run_task = { name = ["book-preprocessors", "book-readme", "book-build-inner"] }

[tasks.book-serve]
workspace = false
run_task = { name = ["book-preprocessors", "book-readme", "book-serve-inner"] }

[tasks.book-build-inner]
workspace = false
cwd = "./docs"
install_crate = "mdbook"
command = "mdbook"
args = ["build"]

[tasks.book-serve-inner]
workspace = false
cwd = "./docs"
install_crate = "mdbook"
command = "mdbook"
args = ["serve"]

